class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'smirror'
        self.UnzipMirrorCommand = 'sunzipmirror'
        self.TarMirrorCommand = 'starmirror'
        self.ZipMirrorCommand = 'szipmirror'
        self.CancelMirror = 'scancel'
        self.CancelAllCommand = 'scancelall'
        self.ListCommand = 'slist'
        self.StatusCommand = 'sstatus'
        self.AuthorizedUsersCommand = 'susers'
        self.AuthorizeCommand = 'sauthorize'
        self.UnAuthorizeCommand = 'sunauthorize'
        self.AddSudoCommand = 'saddsudo'
        self.RmSudoCommand = 'srmsudo'
        self.PingCommand = 'sping'
        self.RestartCommand = 'srestart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'shelp'
        self.LogCommand = 'slog'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'sclone'
        self.WatchCommand = 'swatch'
        self.TarWatchCommand = 'starwatch'
        self.DeleteCommand = 'sdel'
        self.TsHelpCommand = 'stshelp'

BotCommands = _BotCommands()
